src/Entity/Exam.php
<?php

namespace App\Entity;

use App\Repository\ExamRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ExamRepository::class)]
class Exam
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'exams')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Subject $Subject = null;

    #[ORM\ManyToOne(inversedBy: 'exams')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Classroom $Classroom = null;

    #[ORM\ManyToOne(inversedBy: 'exams')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Examtype $Examtype = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $Date = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $startTime = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $endTime = null;

    #[ORM\Column]
    private ?int $totalQuestions = null;

    #[ORM\Column]
    private ?int $totalMarks = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $Duration = null;

    /**
     * @var Collection<int, Results>
     */
    #[ORM\OneToMany(targetEntity: Results::class, mappedBy: 'Exam')]
    private Collection $results;

    /**
     * @var Collection<int, Responses>
     */
    #[ORM\OneToMany(targetEntity: Responses::class, mappedBy: 'Exam', orphanRemoval: true)]
    private Collection $responses;

    #[ORM\Column]
    private ?int $theoryQuestions = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $theoryDuration = null;

    public function __construct()
    {
        $this->results = new ArrayCollection();
        $this->responses = new ArrayCollection();
    }

    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartTime(): ?\DateTimeInterface
    {
        return $this->startTime;
    }

    public function setStartTime(\DateTimeInterface $startTime): static
    {
        $this->startTime = $startTime;

        return $this;
    }

    public function getEndTime(): ?\DateTimeInterface
    {
        return $this->endTime;
    }

    public function setEndTime(\DateTimeInterface $endTime): static
    {
        $this->endTime = $endTime;

        return $this;
    }

    public function getSubject(): ?Subject
    {
        return $this->Subject;
    }

    public function setSubject(?Subject $Subject): static
    {
        $this->Subject = $Subject;

        return $this;
    }

    public function getClassroom(): ?Classroom
    {
        return $this->Classroom;
    }

    public function setClassroom(?Classroom $Classroom): static
    {
        $this->Classroom = $Classroom;

        return $this;
    }

    public function getExamtype(): ?Examtype
    {
        return $this->Examtype;
    }

    public function setExamtype(?Examtype $Examtype): static
    {
        $this->Examtype = $Examtype;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): static
    {
        $this->Date = $Date;

        return $this;
    }

    public function getTotalQuestions(): ?int
    {
        return $this->totalQuestions;
    }

    public function setTotalQuestions(int $totalQuestions): static
    {
        $this->totalQuestions = $totalQuestions;

        return $this;
    }

    public function getTotalMarks(): ?int
    {
        return $this->totalMarks;
    }

    public function setTotalMarks(int $totalMarks): static
    {
        $this->totalMarks = $totalMarks;

        return $this;
    }

    public function getDuration(): ?\DateTimeInterface
    {
        return $this->Duration;
    }

    public function setDuration(\DateTimeInterface $Duration): static
    {
        $this->Duration = $Duration;

        return $this;
    }

    /**
     * @return Collection<int, Results>
     */
    public function getResults(): Collection
    {
        return $this->results;
    }

    public function addResult(Results $result): static
    {
        if (!$this->results->contains($result)) {
            $this->results->add($result);
            $result->setExam($this);
        }

        return $this;
    }

    public function removeResult(Results $result): static
    {
        if ($this->results->removeElement($result)) {
            // set the owning side to null (unless already changed)
            if ($result->getExam() === $this) {
                $result->setExam(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Responses>
     */
    public function getResponses(): Collection
    {
        return $this->responses;
    }

    public function addResponse(Responses $response): static
    {
        if (!$this->responses->contains($response)) {
            $this->responses->add($response);
            $response->setExam($this);
        }

        return $this;
    }

    public function removeResponse(Responses $response): static
    {
        if ($this->responses->removeElement($response)) {
            // set the owning side to null (unless already changed)
            if ($response->getExam() === $this) {
                $response->setExam(null);
            }
        }

        return $this;
    }

    public function getTheoryQuestions(): ?int
    {
        return $this->theoryQuestions;
    }

    public function setTheoryQuestions(int $theoryQuestions): static
    {
        $this->theoryQuestions = $theoryQuestions;

        return $this;
    }

    public function getTheoryDuration(): ?\DateTimeInterface
    {
        return $this->theoryDuration;
    }

    public function setTheoryDuration(\DateTimeInterface $theoryDuration): static
    {
        $this->theoryDuration = $theoryDuration;

        return $this;
    }
}

src/Entity/Student.php
<?php

namespace App\Entity;

use App\Repository\StudentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StudentRepository::class)]
class Student
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $Lastname = null;

    #[ORM\Column(length: 255)]
    private ?string $Middlename = null;

    #[ORM\ManyToOne(inversedBy: 'students')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Classroom $classroom = null;


    #[ORM\Column(length: 255)]
    private ?string $Gender = null;

    #[ORM\Column(type: Types::JSON)]
    private array $Roles = [];

    #[ORM\Column]
    private ?int $admissionYear = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateOfBirth = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $profilePicture = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Email = null;

    /**
     * @var Collection<int, Responses>
     */
    #[ORM\OneToMany(targetEntity: Responses::class, mappedBy: 'Student', orphanRemoval: true)]
    private Collection $responses;

    /**
     * @var Collection<int, Results>
     */
    #[ORM\OneToMany(targetEntity: Results::class, mappedBy: 'Student')]
    private Collection $results;

    /**
     * @var Collection<int, Reportsheet>
     */
    #[ORM\OneToMany(targetEntity: Reportsheet::class, mappedBy: 'student')]
    private Collection $reportsheets;

    public function __construct()
    {
        $this->responses = new ArrayCollection();
        $this->results = new ArrayCollection();
        $this->reportsheets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->Firstname;
    }

    public function setFirstname(string $Firstname): static
    {
        $this->Firstname = $Firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->Lastname;
    }

    public function setLastname(string $Lastname): static
    {
        $this->Lastname = $Lastname;

        return $this;
    }

    public function getMiddlename(): ?string
    {
        return $this->Middlename;
    }

    public function setMiddlename(string $Middlename): static
    {
        $this->Middlename = $Middlename;

        return $this;
    }

    public function getClassroom(): ?Classroom
    {
        return $this->classroom;
    }

    public function setClassroom(?Classroom $classroom): static
    {
        $this->classroom = $classroom;

        return $this;
    }


    public function getGender(): ?string
    {
        return $this->Gender;
    }

    public function setGender(string $Gender): static
    {
        $this->Gender = $Gender;

        return $this;
    }

    public function getRoles(): array
    {
        return $this->Roles;
    }

    public function setRoles(array $Roles): static
    {
        $this->Roles = $Roles;

        return $this;
    }

    public function getAdmissionYear(): ?int
    {
        return $this->admissionYear;
    }

    public function setAdmissionYear(int $admissionYear): static
    {
        $this->admissionYear = $admissionYear;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->dateOfBirth;
    }

    public function setDateOfBirth(\DateTimeInterface $dateOfBirth): static
    {
        $this->dateOfBirth = $dateOfBirth;

        return $this;
    }

    public function getAge(): int
{
    return $this->dateOfBirth ? (new \DateTime())->diff($this->dateOfBirth)->y : 0; // returns 0 if dateOfBirth is null
}

    public function getProfilePicture(): ?string
    {
        return $this->profilePicture;
    }

    public function setProfilePicture(?string $profilePicture): static
    {
        $this->profilePicture = $profilePicture;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): static
    {
        $this->Email = $Email;

        return $this;
    }

    /**
     * @return Collection<int, Responses>
     */
    public function getResponses(): Collection
    {
        return $this->responses;
    }

    public function addResponse(Responses $response): static
    {
        if (!$this->responses->contains($response)) {
            $this->responses->add($response);
            $response->setStudent($this);
        }

        return $this;
    }

    public function removeResponse(Responses $response): static
    {
        if ($this->responses->removeElement($response)) {
            // set the owning side to null (unless already changed)
            if ($response->getStudent() === $this) {
                $response->setStudent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Results>
     */
    public function getResults(): Collection
    {
        return $this->results;
    }

    public function addResult(Results $result): static
    {
        if (!$this->results->contains($result)) {
            $this->results->add($result);
            $result->setStudent($this);
        }

        return $this;
    }

    public function removeResult(Results $result): static
    {
        if ($this->results->removeElement($result)) {
            // set the owning side to null (unless already changed)
            if ($result->getStudent() === $this) {
                $result->setStudent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Reportsheet>
     */
    public function getReportsheets(): Collection
    {
        return $this->reportsheets;
    }

    public function addReportsheet(Reportsheet $reportsheet): static
    {
        if (!$this->reportsheets->contains($reportsheet)) {
            $this->reportsheets->add($reportsheet);
            $reportsheet->setStudent($this);
        }

        return $this;
    }

    public function removeReportsheet(Reportsheet $reportsheet): static
    {
        if ($this->reportsheets->removeElement($reportsheet)) {
            // set the owning side to null (unless already changed)
            if ($reportsheet->getStudent() === $this) {
                $reportsheet->setStudent(null);
            }
        }

        return $this;
    }


}

templates/student/dashboard.html.twig
{% extends 'xbase.html.twig' %}

{% block title %}Student Dashboard{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/dashboard.css') }}">
{% endblock %}

{% block content %}

<div class="full container-fluid"  style="max-width: 100vw; overflow: hidden;" >


   <div class="row">
            <!-- Left Side:-->
            <div class="col-sm-9 col-md-9" style="padding: 20px;">


            <div id="slogo" style="text-align: center; margin-bottom: 20px;">
                <!-- Put logo here -->
                <img src="uploads\Schoollogo\window.jpg" alt="Logo" class="img-fluid">
            </div>
            
            <div id="container" style="margin: auto; margin-top: 50px; max-width: 700px;">
            <div class="centered-section" style=" width:700px;">
             {% if hasExamToday and exams is not empty %}
            <h5><strong>You Have (Atleast) An Exam Today.</strong></h5>
            <div class="exam-container" style="display: flex; overflow-x: auto; gap: 10px; padding: 1px;">
               {% for examData in exams %}
                    <div class="exam-card" style="flex: 0 0 auto; padding: 4px; border: 1px solid #007bff; border-radius: 5px; min-width: 250px; background-color: #f9f9f9;">
                        <h4><strong>{{ examData.exam.subject.course }}</strong></h4>
                        <p><strong>{{ examData.exam.classroom.classname }} - {{ examData.exam.examtype.name }}</strong></p>
            
                        <p><strong> {{ examData.exam.starttime|date('g:i A') }} - {{ examData.exam.endtime|date('g:i A') }}</strong></p>
                        <a href= "{{ path('student_examobjective', {'examToken': examData.examToken}) }}" class="btn btn-primary btn-sm">Start Exam</a>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <h3>You do not have an exam today.</h3>
            <a href="{{ path('student_logout') }}" class="btn btn-primary">Logout</a>
        {% endif %}
    </div>
    </div>

</div>

        

        <!-- Right Side: Exam Content -->
            <div class="col-sm-3 col-md-3" style="background-color: white; padding: 20px; border-radius: 10px; height: 95vh; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);"> <!-- White background for right grid -->
            
            <strong><p style="text-align:left; font-size:12px; font-family:inter; margin-top: 10px; margin-left:5px;"> Exam / Test Date </p></strong>
          
            <div class="calender-section">
             <div id="examCalendar" class="calendar"  style=" margin-top:-10px; margin-left:30px;"></div>
                </div>

           <div class="cal-section">
             <div id="examDetails" class="exam-details-section" style="white-space: nowrap; overflow-x: auto; display: flex; padding: 1px; gap: 10px; background-color: #f9f9f9; border-radius: 10px;">
                    <!-- Exam cards will be dynamically inserted here -->
                </div>

            </div>
            <hr>

    
        <!-- Student Profile on the Left -->
       
            <div class="student-profile" style="text-align: center; margin-top:100px;">
                <img src="/" alt="Profile Picture" class="img-thumbnail" style="width: 50px; height: 50px; border-radius: 50%;"/>
                <p>{{ student.name }}</p>
            </div>
        
        <!-- Logout Button on the Right -->
            <a href="{{ path('student_logout') }}" class="glyphicon glyphicon-log-out">
             Logout
            </a>


        </div>





    </div>
</div>


<script>
  $(document).ready(function () {
    // Fetch exam dates dynamically from the backend
    $.ajax({
        url: '/student/fetch-examdates', // Backend route
        method: 'GET',
        success: function (data) {
            // Extract the 'date' field from each item
            const examDates = data.map(item => item.Date.date.split(" ")[0]); // Extract 'YYYY-MM-DD'

            // Initialize the datepicker after fetching data
            $("#examCalendar").datepicker({
                format: "yyyy-mm-dd", // Date format for Bootstrap Datepicker
                todayHighlight: true, // Highlight today's date
                beforeShowDay: function (date) {
                    const formattedDate = date.toLocaleDateString('en-CA').split("T")[0]; // Format date for comparison
                    if (examDates.includes(formattedDate)) {
                        return {
                            classes: "exam-date", // Add CSS class
                            tooltip: "Exam Date" // Tooltip
                        };
                    }
                    return true; // Default behavior
                }
            });
        },
        error: function () {
            console.error("Failed to fetch exam dates.");
        }
    });
});




$(document).ready(function () {
    $.ajax({
        url: '/student/fetch-todayexams',
        method: 'GET',
        success: function (data) {
            if (data.message) {
                $("#examDetails").html(`<p>${data.message}</p>`);
            } else if (data.length > 0) {
                let examHtml = '';
                data.forEach(exam => {
                    const examDate = new Date(exam.date); // Convert date to JavaScript Date object
                    const startTime = new Date(`${exam.date}T${exam.start_time}`);
                    const endTime = new Date(`${exam.date}T${exam.end_time}`);

                    // Format date and time
                    const dayName = examDate.toLocaleString('en-US', { weekday: 'long' });
                    const startTimeFormatted = startTime.toLocaleString('en-US', { hour: 'numeric', minute: 'numeric', hour12: true });
                    const endTimeFormatted = endTime.toLocaleString('en-US', { hour: 'numeric', minute: 'numeric', hour12: true });

                    // Add a card for the exam
                    examHtml += `
                        <div class="exam-card" style="display: inline-block; padding: 15px; background-color: #fff; border: 1px solid #ccc; border-left:5px solid  #007bff; border-radius: 10px; min-width: 200px; height:70px; text-align:left;">
                            <h4 style="margin-top:-7px; margin-left:-5px;">${exam.subject}</h4>
                            <p style="margin-top:-7px; margin-left:-5px;"><strong>${dayName}:</strong> ${startTimeFormatted} - ${endTimeFormatted}</p>  
                            <h6  style="margin-top:-7px; margin-left:-5px;">${exam.classroom}</h6>
                        </div>
                    `;
                });
                $("#examDetails").html(examHtml);
            } else {
                $("#examDetails").html('<p>No exams today.</p>');
            }
        },
        error: function () {
            console.error("Failed to fetch exams.");
        }
    });
});






</script>

<style>
.container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    min-height: 100vh; /* Vertically centers content */
    padding: 20px;
}

.centered-section {
    width: 300px; /* Sets a consistent, smaller width */
    max-width: 90%; /* Ensures responsiveness on smaller screens */
    background-color: white;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Subtle shadow for styling */
    text-align: center;
    margin-bottom: 10px; /* Adds spacing between the sections */
}


.cal-section {
    max-width: 250px;        /* Limit the width */
}

.current-exam p {
    margin-top:10px;
    margin: 0;
    font-size: 10px; /* Slightly larger text */
    color: #333;     /* Darker text color */
    border:2px solid blue;
}

.calendar-section strong {
    color: #007bff; /* Bootstrap primary color */
}

.calendar {
    text-align: center; /* Center the calendar */
    background-color: #ffffff; /* White background for calendar */
    border-radius: 5px;
}

/* General styling for the datepicker container */
    .datepicker {
        font-size: 9px; /* Smaller font size */
        width: 200px; /* Adjust width */
        padding: 1px; /* Adjust padding */
    }

    /* Adjust the header (month and year) */
    .datepicker .datepicker-switch {
        font-size: 14px; /* Slightly larger font for the header */
        padding: 5px 10px; /* Adjust padding */
    }

    /* Style the day cells */
    .datepicker table tr td,
    .datepicker table tr th {
        width: 30px; /* Adjust day cell width */
        height: 10px; /* Adjust day cell height */
        text-align: center; /* Center align text */
        color:#007bff ;
        padding: 3px; /* Adjust padding */
    }

    /* Highlight today's date */
    .datepicker table tr td.today {
        background-color: #007bff ;
        color: white;
        border-radius: 100%; 
        width:15px;
        height:15px;/* Circular highlight */
    }

    /* Adjust the navigation arrows */
    .datepicker .prev, 
    .datepicker .next {
        font-size: 12px; /* Smaller arrows */
        padding: 5px;
    }


    .exam-date {
        background-color: #007bff !important;
        color: white !important;
        width:10px;
        height:20px;
        border-radius: 100% !important; /* Circular shape */
    }

    .exam-date:hover {
        background-color: darkblue !important; /* Darker on hover */
    }
    .glyphicon-log-out{
        text-align:center;
        font-size:15px;
        
    }

    .table-condensed{
        margin-left:40px;
    }
 

 
</style>

{% endblock %}

templates/student/examresult.html.twig
{% extends 'xbase.html.twig' %}

{% block title %} My Result {% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/student.css') }}">
{% endblock %}

{% block content %}
<div class="full container-fluid">
    


<div class="button-container">
    <a  class="btn btn-default btm"> <span class="glyphicon glyphicon-file"></span> Objective</a>
    <a  class="btn btn-default btm"> <span class="glyphicon glyphicon-file"></span> Theory</a>
    <a  class="btn btn-primary btm"> <span class="glyphicon glyphicon-file"></span> Result</a>
</div>



<div id="student-card" class="card student-info-card" data-grade="{{ grade.grade }}">
    <div class="card-body">
        <div class="row">
    <div class="col-md-4">
        <h1><span class="grade buff">{{ grade.grade }}</span></h1>
    </div>
    <div class="col-md-4">
        <h1><span class="score fat">{{ score }}/{{ exam.totalMarks }}</span></h1>
    </div>
    <div class="col-md-4">
        <h1><span class="percentage buff">{{ percentage }}%</span></h1>
    </div>
</div>

    </div>
</div>


<!-- Feedback Section -->
<div class="alert alert-info text-center mt-4 feedback">
    {% if percentage >= 90 %}
        🎉 Excellent performance {{student.lastname}} ! Keep it up!
    {% elseif percentage >= 70 %}
        👍 Good job {{student.lastname}} ! You're doing well.
    {% elseif percentage >= 50 %}
        👏 Not bad {{student.lastname}} ! You’re getting there, keep it up.
    {% else %}
        📚 Keep practicing {{student.lastname}} ! You've got this. Every step counts.
    {% endif %}
</div>

<div class="row">
    <!-- Left Column: Student Performance Breakdown -->
   <div class="col-md-6">
    <div class="performance-breakdown">
        <!-- Dropdowns -->
        <div class="form-inline mb-3">
            <select id="subject" class="form-control form-control-sm mr-3" disabled>
                <option>{{ exam.subject.course }}</option>
            </select>
            <select id="class" class="form-control form-control-sm mr-3" disabled>
                <option>{{ exam.classroom.classname }}</option>
            </select>
            <select id="examType" class="form-control form-control-sm" disabled>
                <option>{{ exam.examType.name }}</option>
            </select>
        </div>

      <!-- Performance Rings -->
<div class="ring-container">
    <!-- Total Questions -->
    <div class="ring-wrapper">
        <div class="ring" style="border-color: green;">
            <span class="ring-text">{{ totalQuestions }}</span>
        </div>
        <p class="ring-label">Total</p>
    </div>

    <!-- Total Answered -->
    <div class="ring-wrapper">
        <div class="ring" style="border-color: blue;">
            <span class="ring-text">{{ answeredQuestions }}</span>
        </div>
        <p class="ring-label">Answered</p>
    </div>

    <!-- Correct Answers -->
    <div class="ring-wrapper">
        <div class="ring" style="border-color: green;">
            <span class="ring-text">{{ correctAnswers }}</span>
        </div>
        <p class="ring-label">Correct</p>
    </div>

    <!-- Incorrect Answers -->
    <div class="ring-wrapper">
        <div class="ring" style="border-color: red;">
            <span class="ring-text">{{ incorrectAnswers }}</span>
        </div>
        <p class="ring-label">Incorrect</p>
    </div>

    <!-- Unattempted -->
    <div class="ring-wrapper">
        <div class="ring" style="border-color: grey;">
            <span class="ring-text">{{ totalQuestions - answeredQuestions }}</span>
        </div>
        <p class="ring-label">Unattempted</p>
    </div>
</div>
</div>
</div>



    <!-- Right Column: Class Leaderboard -->
    <div class="col-md-6">
        <div class="leaderboard">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Rank</th>
                        <th>Student</th>
                        <th>Percentage</th>
                    </tr>
                </thead>
                <tbody>
                    {% for leaderboardEntry in leaderboard %}
                    <tr>
                        <td>{{ loop.index }}</td>
                        <td>{{ leaderboardEntry.student.lastname }}</td>
                        <td>{{ leaderboardEntry.percentage }}%</td>
                    </tr>
                    {% else %}
                    <tr>
                        <td colspan="4">No leaderboard data available.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <h5 style="align:inline-start">Class Leaderboard</h5> | <a href="{{ path('student_logout') }}" class="glyphicon glyphicon-log-out">  Logout</a>
        </div>
    </div>
</div>






<script>
    $(document).ready(function () {
        const grade = $('#student-card').data('grade').toUpperCase();

        let colorClass = '';
        switch (grade) {
            case 'A1':
            case 'A2':
                colorClass = 'bg-success text-white'; // Green for excellent grades
                break;
            case 'B3':
            case 'B4':
            case 'C5':
                colorClass = 'bg-primary text-white'; // Blue for good grades
                break;
            case 'C6':
            case 'D7':
                colorClass = 'bg-warning text-dark'; // Yellow for average grades
                break;
            case 'E8':
            case 'F9':
                colorClass = 'bg-danger text-white'; // Red for failing grades
                break;
            default:
                colorClass = 'bg-secondary text-white'; // Grey for undefined grades
        }

        $('#student-card').addClass(colorClass);
    });
</script>

</div>

{% endblock %}

templates/student/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Student Login - MyExamSpace.Com{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/styles.css') }}">
{% endblock %}

{% block auth %}
<div class="adjust">
    <div class="loginform">
        <h1 id="who">Student Login</h1>

       {# Display error message if present #}
    {% if error %}
        <div class="alert alert-danger">{{ error }}</div>
    {% endif %}


        {# Form starts here #}
        <form action="{{ path('student_access') }}" method="POST">
            <div class="form-group">
                <label for="firstname">First Name</label>
                <span class="glyphicon glyphicon-user gly"></span>
                <input type="text" name="_Firstname" id="firstname" class="form-control signup" 
                 required pattern="[A-Za-z]+" title="Please enter only letters.">
            </div>

            <div class="form-group">
                <label for="lastname">Last Name</label>
                <span class="glyphicon glyphicon-user gly"></span>
                <input type="text" name="_Lastname" id="lastname" class="form-control signup"
                 required pattern="[A-Za-z]+" title="Please enter only letters.">
            </div>


               <div class="form-group">
                <label for="classroom">Classroom</label>
                <span class="glyphicon glyphicon-list gly"></span>
                <select name="_classroom" id="classroom" class="form-control signup" required>
                    <option value="">Select Classroom</option>
                    {% for classroom in classrooms %}
                        <option value="{{ classroom.id }}">
                            {% if classroom.department is not null %}
                                {{ classroom.department.department }} - 
                            {% endif %}
                            {{ classroom.classname }}
                        </option>
                    {% endfor %}
                </select>
            </div>

            {# Include CSRF token for security #}
            <input type="hidden" name="_csrf_token" value="{{ csrf_token('access') }}">

            <input type="submit" value="Login" class="btn btn-primary space">
        </form>
    </div>
</div>
{% endblock %}

{% block pp %}
<div class="imgcontainer">
    <img src="{{ asset('images/student.jfif') }}" alt="student Image" class="imge">
</div>
{% endblock %}